name: '4347'
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.6.0=h6a678d5_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.18.4=h44eff21_0
  - comm=0.2.3=pyhe01879c_0
  - dav1d=1.2.1=h5eee18b_0
  - debugpy=1.8.16=py39haef64b4_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - ffmpeg=6.1.1=h2a67f75_3
  - fontconfig=2.14.1=h55d465d_3
  - freetype=2.13.3=h4a9f257_0
  - giflib=5.2.2=h5eee18b_0
  - graphite2=1.3.14=h295c915_1
  - harfbuzz=10.2.0=hdfddeaa_1
  - icu=73.1=h6a678d5_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.30.1=pyh82676e8_0
  - ipython=8.18.1=pyh707e725_3
  - jedi=0.19.2=pyhd8ed1ab_1
  - jpeg=9e=h5eee18b_3
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - krb5=1.21.3=h723845a_4
  - lame=3.100=h7b6447c_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - leptonica=1.82.0=hfdeec58_3
  - lerc=4.0.0=h6a678d5_0
  - libarchive=3.7.7=hfab0078_0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.1.0=h767d61c_5
  - libgcc-ng=15.1.0=h69a702a_5
  - libglib=2.84.2=h37c7471_0
  - libgomp=15.1.0=h767d61c_5
  - libiconv=1.16=h5eee18b_3
  - libkrb5=1.21.3=h520c7b4_4
  - libogg=1.3.5=h27cfd23_1
  - libopus=1.3.1=h5eee18b_1
  - libpng=1.6.39=h5eee18b_0
  - libsodium=1.0.20=h4ab18f5_0
  - libstdcxx=15.1.0=h8f9b012_5
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtheora=1.1.1=h7f8727e_3
  - libtiff=4.7.0=hde9077f_0
  - libuuid=1.41.5=h5eee18b_0
  - libvorbis=1.3.7=h7b6447c_0
  - libvpx=1.13.1=h6a678d5_0
  - libwebp=1.3.2=h9f374a3_1
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.8=hfdd30dd_0
  - lmdb=0.9.31=hd590300_1
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=h0d4d230_1
  - openssl=3.5.4=h26f9b46_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.2=pyhc872135_0
  - pixman=0.46.4=h7934f7d_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=7.0.0=py39h8cd3c5a_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.9.23=he99959a_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.9=2_cp39
  - pyzmq=27.0.2=py39haa5fa38_0
  - readline=8.3=hc2a1206_0
  - setuptools=78.1.1=py39h06a4308_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.50.2=hb25bd0a_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tesseract=5.2.0=h6a678d5_2
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.2=py39hd399759_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.14.1=pyhe01879c_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=py39h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=h3989a48_8
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.1
      - aiosignal==1.4.0
      - alembic==1.16.5
      - antlr4-python3-runtime==4.9.3
      - asteroid-filterbanks==0.4.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - audioread==3.0.1
      - av==12.3.0
      - certifi==2022.12.7
      - cffi==1.17.1
      - chardet==5.2.0
      - charset-normalizer==2.1.1
      - click==8.1.8
      - cmake==3.25.0
      - coloredlogs==15.0.1
      - colorlog==6.10.1
      - contourpy==1.3.0
      - ctranslate2==4.6.0
      - cycler==0.12.1
      - docopt==0.6.2
      - einops==0.8.1
      - faster-whisper==1.0.3
      - ffmpeg-python==0.2.0
      - filelock==3.13.1
      - flatbuffers==25.9.23
      - fonttools==4.59.2
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - future==1.0.0
      - greenlet==3.2.4
      - hf-xet==1.1.10
      - huggingface-hub==0.34.4
      - humanfriendly==10.0
      - hyperpyyaml==1.2.2
      - idna==3.4
      - importlib-resources==6.5.2
      - jinja2==3.1.4
      - joblib==1.5.2
      - julius==0.2.7
      - kiwisolver==1.4.7
      - librosa==0.9.2
      - lightning==2.5.5
      - lightning-utilities==0.15.2
      - lit==15.0.7
      - llvmlite==0.43.0
      - mako==1.3.10
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.4
      - mdurl==0.1.2
      - mido==1.3.0
      - mir-eval==0.7
      - mpmath==1.3.0
      - multidict==6.7.0
      - networkx==3.2.1
      - nltk==3.9.2
      - numba==0.60.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - onnxruntime==1.19.2
      - optuna==4.5.0
      - packaging==23.2
      - pandas==2.2.3
      - pillow==11.0.0
      - platformdirs==4.4.0
      - pooch==1.8.2
      - primepy==1.3
      - propcache==0.4.1
      - protobuf==6.33.0
      - pyannote-audio==3.1.1
      - pyannote-core==5.0.0
      - pyannote-database==5.1.3
      - pyannote-metrics==3.2.1
      - pyannote-pipeline==3.0.1
      - pycparser==2.22
      - pyparsing==3.2.3
      - pytorch-lightning==2.5.5
      - pytorch-metric-learning==2.9.0
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2025.9.1
      - requests==2.28.1
      - resampy==0.4.3
      - rich==14.2.0
      - ruamel-yaml==0.18.15
      - ruamel-yaml-clib==0.2.12
      - safetensors==0.6.2
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - semver==3.0.4
      - sentencepiece==0.2.1
      - shellingham==1.5.4
      - sortedcontainers==2.4.0
      - soundfile==0.12.1
      - soxr==1.0.0
      - speechbrain==1.0.3
      - sqlalchemy==2.0.44
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboardx==2.6.4
      - threadpoolctl==3.6.0
      - tokenizers==0.22.1
      - tomli==2.3.0
      - torch==2.6.0+cu124
      - torch-audiomentations==0.12.0
      - torch-pitch-shift==1.2.5
      - torchaudio==2.6.0+cu124
      - torchmetrics==1.8.2
      - torchvision==0.21.0+cu124
      - tqdm==4.66.1
      - transformers==4.57.1
      - triton==3.2.0
      - typer==0.19.2
      - typing-extensions==4.12.2
      - tzdata==2025.2
      - urllib3==1.26.13
      - whisperx==3.1.1
      - yarl==1.22.0
prefix: /home/young/anaconda3/envs/4347
